export const PREFERENCE_KEYS = {
  OVERLAYS_ENABLED: "ff-overlays-enabled",
  OVERLAY_ENABLED: "ff-overlay-enabled",
  OVERLAY_PRIORITY: "ff-overlay-priority",
  OVERLAY_OFFSETS: "ff-overlay-offsets",
  RIVEN_OVERLAY_ENABLED: "ff-riven-overlay-enabled",
  TEXT_SCALE: "ff-text-scale",
  COLORBLIND_MODE: "ff-colorblind",
  INVENTORY_VIEW: "ff-view-inventory",
  INVENTORY_CARD_COLUMNS: "ff-inventory-card-columns",
  INVENTORY_LIST_TEXT_SCALE: "ff-inventory-list-text-scale",
  FOUNDRY_VIEW: "ff-view-foundry",
  RELIC_VIEW: "ff-view-relic",
  ITEM_REPORT_ORDER: "ff-item-report-order",
} as const;
