export const TAURI_EVENTS = {
  SETTINGS_UPDATED: "settings-updated",
  RELIC_TRIGGER: "relic-trigger",
  RELIC_REWARDS: "relic-rewards",
  RELIC_SCREEN: "relic-screen",
  RELIC_PICK_OPEN: "relic-pick-open",
  RELIC_PICK_CLOSE: "relic-pick-close",
  RIVEN_MANUAL_CHECK: "riven-manual-check",
  RIVEN_WINDOW_READY: "riven-window-ready",
  RIVEN_ANALYSIS_UPDATE: "riven-analysis-update",
  RIVEN_ROLL_SAVED: "riven-roll-saved",
  RIVEN_OVERLAY_HIDE: "riven-overlay-hide",
  RIVEN_SCANNING_START: "riven-scanning-start",
  RIVEN_SCREEN_OPEN: "riven-screen-open",
  RIVEN_SCREEN_CLOSE: "riven-screen-close",
  RIVEN_UNVEILED: "riven-unveiled",
  INVENTORY_UPDATE: "inventory-update",
  INVENTORY_REWARD: "inventory-reward",
  CATALOGUE_UPDATED: "catalogue-updated",
  BULK_PRICES_UPDATED: "bulk-prices-updated",
  TRADE_COMPLETED: "trade-completed",
  TRADES_UPDATED: "trades-updated",
  BLOB_STATUS: "blob-status",
  CACHE_STATUS: "cache-status",
  CONSOLE_LOGIN_SUCCESS: "console-login-success",
  FF_STATUS: "ff-status",
  PLAYER_NAME: "player-name",
  WFM_WHISPER: "wfm-whisper",
  WFM_PRICE_UPDATE: "wfm-price-update",
  WFM_TOP_PROGRESS: "wfm-top-progress",
  WFM_TOP_UPDATED: "wfm-top-updated",
  OVERLAY_OUTLINE: "overlay-outline",
  ARBITRATION_RUN_ENDED: "arbitration-run-ended",
  ARBITRATION_RUNS_CHANGED: "arbitration-runs-changed",
} as const;

// Feature 3 — api.warframe.com/api/inventory.php
// DE confirmed third-party tools are used "at your own risk" but could not clarify
// whether accessing this undocumented endpoint specifically is permitted.
// Set to false to re-enable once clearer guidance is received.
export const COMPANION_API_SUSPENDED = true;

export const TAURI_COMMANDS = {
  SAVE_SETTINGS: "save_settings",
  GET_CURRENT_QUANTITIES: "get_current_quantities",
  GET_RECIPES_BULK: "get_recipes_bulk",
  SAVE_RIVEN_ROLL: "save_riven_roll",
  MOVE_OVERLAY_OFFSCREEN: "move_overlay_offscreen",
  OPEN_URL: "plugin:opener|open_url",
  ADD_TRADE: "add_trade",
  ANALYZE_RIVEN: "analyze_riven",
  FETCH_WFM_ITEMS: "fetch_wfm_items",
  GET_ALL_ITEMS: "get_all_items",
  GET_BULK_PRICES: "get_bulk_prices",
  GET_CRAFTABLE_ITEMS: "get_craftable_items",
  GET_RECIPE: "get_recipe",
  GET_WFM_TOP_ITEMS: "get_wfm_top_items",
  LOAD_SETTINGS: "load_settings",
  LOG_RELIC_FE: "log_relic_fe",
  SAVE_API_INVENTORY: "save_api_inventory",
  SET_MEM_TRIGGER_ENABLED: "set_mem_trigger_enabled",
  SET_RELIC_PICK_ENABLED: "set_relic_pick_enabled",
  SET_ARBITRATION_OVERLAY_ENABLED: "set_arbitration_overlay_enabled",
  WFM_CREATE_ORDER: "wfm_create_order",
  WFM_GET_ITEM_INFO: "wfm_get_item_info",
  WFM_GET_SESSION: "wfm_get_session",
  WFM_LOAD_CREDENTIALS: "wfm_load_credentials",
  WFM_SET_JWT: "wfm_set_jwt",
  WFM_SET_STATUS: "wfm_set_status",
} as const;
